#   Please use following command  to start ->  docker-compose up --build -d
#  This command to stop                    ->  docker-compose down
#todo add environment variables

version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: martins_api_db
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: martinsapi
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - martins_network
    restart: always

  redis:
    image: redis:6.2
    container_name: martins_api_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - martins_network
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: martins_api_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - martins_network
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: martins_api_kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - martins_network
    restart: always

networks:
  martins_network:
    driver: bridge

volumes:
  db_data:
  redis_data:
